<?php
declare(strict_types=1);

require_once __DIR__ . '/bootstrap.php';

$txServices = [
    [
        'slug' => 'pagina-web',
        'name' => 'Página web informativa',
        'category' => 'Desarrollo y software',
        'image' => '/assets/img/services/web-development.webp',
        'image_alt' => 'Desarrollador trabajando con código en un computador portátil.',
        'summary' => 'Diseño y desarrollo de sitios corporativos adaptados a celulares, con estructura de contenido y publicación.',
        'scope' => 'Sitio informativo definido en la cotización.',
        'includes' => 'Diseño responsive, páginas acordadas, formulario y publicación.',
        'excludes' => 'Contenido, fotografías, dominio y licencias no descritas.',
        'price' => 'Según número de páginas, contenido, idiomas e integraciones; se fija en la cotización.',
        'delivery' => 'Plazo indicado en la propuesta según cantidad de páginas y materiales.',
        'requirements' => 'Identidad visual, textos, imágenes, accesos y aprobación oportuna.',
        'support' => 'Corrección de errores del alcance durante el periodo indicado en la cotización.',
        'cancellation' => 'Sujeta al avance realizado y a la política de reembolsos.',
    ],
    [
        'slug' => 'tienda-virtual',
        'name' => 'Tienda virtual',
        'category' => 'Desarrollo y software',
        'image' => '/assets/img/services/ecommerce.webp',
        'image_alt' => 'Panel de gestión de comercio electrónico abierto en un portátil.',
        'summary' => 'Catálogo, carrito, pedidos y conexión con medios de pago según las necesidades del comercio.',
        'scope' => 'Comercio electrónico con módulos definidos previamente.',
        'includes' => 'Catálogo, administración básica, pedidos y configuración acordada.',
        'excludes' => 'Comisiones de pasarela, logística, inventario y servicios de terceros.',
        'price' => 'Según catálogo, módulos, pasarela e integraciones; se fija en la cotización.',
        'delivery' => 'Plazo establecido luego de revisar catálogo e integraciones.',
        'requirements' => 'Productos, precios, políticas, medios de pago y datos de entrega.',
        'support' => 'Soporte de implementación y garantía según alcance contratado.',
        'cancellation' => 'Los costos de terceros y trabajo ejecutado pueden descontarse.',
    ],
    [
        'slug' => 'crm',
        'name' => 'CRM y software empresarial',
        'category' => 'Desarrollo y software',
        'image' => '/assets/img/services/crm-team.webp',
        'image_alt' => 'Equipo de trabajo colaborando con varios computadores.',
        'summary' => 'Herramientas para organizar clientes, conversaciones, tareas, ventas y operación interna.',
        'scope' => 'Módulos y perfiles definidos en levantamiento de requerimientos.',
        'includes' => 'Análisis, desarrollo, pruebas y entrega del alcance aprobado.',
        'excludes' => 'Funciones o integraciones no incluidas en la propuesta.',
        'price' => 'Según módulos, usuarios, migraciones e integraciones; se fija en la cotización.',
        'delivery' => 'Depende de módulos, usuarios, migraciones e integraciones.',
        'requirements' => 'Procesos actuales, responsables, datos de prueba y criterios de aceptación.',
        'support' => 'Corrección de errores del alcance original durante el periodo pactado.',
        'cancellation' => 'Se liquida el trabajo y los servicios de terceros ya ejecutados.',
    ],
    [
        'slug' => 'inventarios',
        'name' => 'Inventarios y desarrollo personalizado',
        'category' => 'Desarrollo y software',
        'image' => '/assets/img/services/inventory.webp',
        'image_alt' => 'Centro logístico con estanterías y productos organizados.',
        'summary' => 'Aplicaciones ajustadas a procesos de inventario, ventas, reportes y administración.',
        'scope' => 'Solución definida mediante requerimientos y criterios de aceptación.',
        'includes' => 'Análisis funcional, desarrollo, pruebas y documentación acordada.',
        'excludes' => 'Cambios posteriores que modifiquen el alcance aprobado.',
        'price' => 'Según módulos, reportes, usuarios y migración de datos; se fija en la cotización.',
        'delivery' => 'Cronograma por etapas incluido en la propuesta.',
        'requirements' => 'Reglas de negocio, usuarios, datos y validaciones del cliente.',
        'support' => 'Acompañamiento inicial y garantía descrita en la orden.',
        'cancellation' => 'Los hitos aceptados y trabajo ejecutado no se tratan como trabajo pendiente.',
    ],
    [
        'slug' => 'automatizacion-whatsapp',
        'name' => 'Automatización de WhatsApp',
        'category' => 'Automatización',
        'image' => '/assets/img/services/whatsapp-automation.webp',
        'image_alt' => 'Persona gestionando mensajes desde un celular y un portátil.',
        'summary' => 'Flujos de atención, asignación, notificaciones e integración con herramientas autorizadas.',
        'scope' => 'Automatización y canales especificados en la cotización.',
        'includes' => 'Configuración del flujo, pruebas y capacitación acordada.',
        'excludes' => 'Tarifas de Meta, Twilio, proveedores de mensajes o números.',
        'price' => 'Según canales, flujos, plantillas, usuarios e integraciones; se fija en la cotización.',
        'delivery' => 'Depende de la aprobación de plantillas, cuentas y proveedores.',
        'requirements' => 'Cuenta habilitada, permisos, número y mensajes aprobados.',
        'support' => 'Soporte sobre la configuración entregada; disponibilidad sujeta a terceros.',
        'cancellation' => 'Las licencias y consumos de terceros no utilizados dependen de su proveedor.',
    ],
    [
        'slug' => 'bots-ia',
        'name' => 'Bots e integraciones con inteligencia artificial',
        'category' => 'Automatización',
        'image' => '/assets/img/services/ai-integration.webp',
        'image_alt' => 'Robot de asistencia con pantalla táctil en funcionamiento.',
        'summary' => 'Asistentes e integraciones configurados para tareas y fuentes de información delimitadas.',
        'scope' => 'Casos de uso, límites y fuentes definidos antes del desarrollo.',
        'includes' => 'Configuración, integración, pruebas y controles descritos.',
        'excludes' => 'Consumo de APIs, licencias y resultados fuera del alcance.',
        'price' => 'Según casos de uso, fuentes, integraciones y consumo previsto; se fija en la cotización.',
        'delivery' => 'Cronograma según integraciones, datos y pruebas requeridas.',
        'requirements' => 'Fuentes autorizadas, accesos, ejemplos y reglas de escalamiento.',
        'support' => 'Ajustes del flujo contratado; los resultados pueden variar según datos y uso.',
        'cancellation' => 'Se descuentan desarrollos, configuraciones y consumos ya realizados.',
    ],
    [
        'slug' => 'servidores',
        'name' => 'Configuración y soporte de servidores',
        'category' => 'Infraestructura y soporte',
        'image' => '/assets/img/services/servers.webp',
        'image_alt' => 'Gabinetes de servidores y cableado dentro de un centro de datos.',
        'summary' => 'Despliegues, migraciones, respaldos y configuración técnica con alcance controlado.',
        'scope' => 'Servidor, servicios y ventanas de trabajo descritas en la orden.',
        'includes' => 'Revisión, configuración, pruebas y entrega de evidencias acordadas.',
        'excludes' => 'Licencias, nube, hardware y soporte continuo no contratado.',
        'price' => 'Según servidores, volumen de datos, servicios y ventana de trabajo; se fija en la cotización.',
        'delivery' => 'Según accesos, volumen de datos y ventana de mantenimiento.',
        'requirements' => 'Accesos autorizados, respaldo, inventario y responsable del cliente.',
        'support' => 'Validación posterior sobre los componentes intervenidos.',
        'cancellation' => 'Las horas ejecutadas y servicios de infraestructura se liquidan.',
    ],
    [
        'slug' => 'reparacion-computadores',
        'name' => 'Reparación de computadores',
        'category' => 'Infraestructura y soporte',
        'image' => '/assets/img/services/computer-repair.webp',
        'image_alt' => 'Componentes internos iluminados de un computador de escritorio.',
        'summary' => 'Diagnóstico y reparación de hardware o software con autorización previa.',
        'scope' => 'Equipo y falla descritos en la recepción o diagnóstico.',
        'includes' => 'Diagnóstico y trabajo expresamente autorizado.',
        'excludes' => 'Repuestos, recuperación de datos o trabajos no aprobados.',
        'price' => 'Se informa después del diagnóstico y antes de reparar.',
        'delivery' => 'Tiempo estimado comunicado tras identificar la falla y disponibilidad.',
        'requirements' => 'Entrega del equipo, accesorios relevantes y autorización del propietario.',
        'support' => 'Garantía sobre el trabajo realizado según diagnóstico y repuesto.',
        'cancellation' => 'El diagnóstico o trabajo autorizado puede generar el cobro informado.',
    ],
    [
        'slug' => 'reparacion-celulares',
        'name' => 'Reparación de celulares',
        'category' => 'Infraestructura y soporte',
        'image' => '/assets/img/services/phone-repair.webp',
        'image_alt' => 'Técnico reparando un teléfono móvil sobre una mesa de trabajo.',
        'summary' => 'Diagnóstico, configuración y reparación de dispositivos móviles.',
        'scope' => 'Intervención autorizada para el dispositivo recibido.',
        'includes' => 'Diagnóstico y reparación aceptada por el cliente.',
        'excludes' => 'Piezas, datos o daños no incluidos en la autorización.',
        'price' => 'Se informa después del diagnóstico y antes de reparar.',
        'delivery' => 'Sujeto al diagnóstico y disponibilidad de repuestos.',
        'requirements' => 'Equipo, accesorios relevantes y prueba de autorización.',
        'support' => 'Garantía limitada al trabajo y repuesto instalados.',
        'cancellation' => 'Aplica el valor de diagnóstico o intervención previamente informado.',
    ],
];

$txFaqs = [
    ['¿Quién presta el servicio?', 'Los servicios son gestionados por Hugo Alberto Ardila Molina, titular del establecimiento de comercio TECNOXPERT, identificado con NIT 1083903212-3.'],
    ['¿Cómo solicito una cotización?', 'Puedes usar el formulario de contacto o WhatsApp. Se revisan los requisitos antes de emitir una propuesta con alcance, plazo, precio y condiciones.'],
    ['¿En qué moneda se cobra?', 'Las cotizaciones nacionales se expresan en pesos colombianos (COP), salvo que la propuesta indique expresamente otra moneda para un servicio internacional.'],
    ['¿Puedo pagar desde otro país?', 'Depende del medio de pago habilitado para la cotización y del país del pagador. La disponibilidad se confirma antes de enviar el enlace de pago.'],
    ['¿Cuándo comienza el trabajo?', 'Después de aceptar la propuesta, completar la información requerida y realizar el anticipo o pago acordado.'],
    ['¿Qué ocurre después del pago?', 'Se verifica la confirmación del proveedor de pago, se actualiza la orden y se comunica el inicio o siguiente etapa del servicio.'],
    ['¿Los anticipos son reembolsables?', 'Se revisa cada caso según la ley, el avance, las licencias adquiridas, los costos de terceros y las condiciones aceptadas.'],
    ['¿Qué incluye la garantía?', 'La garantía cubre lo descrito en la cotización u orden. Los cambios adicionales y fallas causadas por terceros se evalúan por separado.'],
    ['¿Cómo solicito soporte?', 'Escribe a contacto@tecnoxpert.com o al WhatsApp oficial e indica la cotización, orden, equipo o servicio relacionado.'],
    ['¿TECNOXPERT realiza envíos?', 'Solo cuando una cotización o pedido de producto físico lo indique. Antes del pago se informan cobertura, costo, transportadora y plazo estimado.'],
    ['¿Cómo recibo una factura o comprobante?', 'El comprobante o documento correspondiente se entrega con los datos asociados a la orden y al pago confirmado.'],
    ['¿Qué pasa si necesito cambios adicionales?', 'Se revisan y cotizan como ampliación del alcance. No se incorporan automáticamente al precio ni al plazo original.'],
];

function tx_service_by_slug(array $services, string $slug): ?array
{
    foreach ($services as $service) {
        if (($service['slug'] ?? '') === $slug) {
            return $service;
        }
    }
    return null;
}
